### ISSUE TITLE
[Bug] Webpack loader config can't work in require-context.macro

### ISSUE THREAD

**Issue by miaolq** [storybookjs/require-context.macro#122]
### Describe the bug

`requireContext('!@svgr/webpack!../../../assets/svgs', false, /\.(svg)$/)` will treat `!@svgr/webpack!` as path instead of webpack loader options.

### Expected behavior

Treat `!@svgr/webpack!` as webpack loader options

### Environment

 - OS: Mac m1
 - Node.js version: 14.7.0

**Comment by kylemh** [comment]
It was difficult for me going through the Webpack documentation to try and find a type signature for `require.context()`; however, not a single test prefixes any string with a `'!'`.

https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/test/cases/parsing/context/index.js

I'm a little worried that perhaps this isn't desired behavior, since it's _not_ a loader.

**Comment by miaolq** [comment]
Thank you. For now, i will code like this.
```js
const res = IS_TEST
    ? requireContext('../../../assets/svgs', false, /\.(svg)$/)
    : require.context('!@svgr/webpack!assets/svgs', false, /\.(svg)$/);
```
